### ISSUE TITLE
Ты тоже на IT SCHOOL Samsung ходил?

### ISSUE THREAD

**Issue by RazuvaevDD** [mihailk239/FlappyBirdClone#1]
Я тоже туды шастал)))

**Comment by justyxxxhack** [comment]
Ну как-бы да, неужели не похоже?)

**Comment by Donutellko** [comment]
Ещё скажите, что Разуваев и Кудрин не провели десятки часов в непосредственной близости.

**Comment by justyxxxhack** [comment]
Не понял

**Comment by Donutellko** [comment]
Ты Кудрин. Он Разуваев. Вы со мной последний год в одной группе были, разве нет?

**Comment by justyxxxhack** [comment]
Однако ж ты скользкий)) ну в группе то мы в одной были эт да))

**Comment by Donutellko** [comment]
Чот сложно. Янепонимат.
Он написал: о, ты тоже в самсунг ходил?
При том что вы знакомы лично.

**Comment by justyxxxhack** [comment]
Ну, видимо не поймешь.
